# Generated by Django 3.2.5 on 2021-08-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ismi...')),
                ('number', models.CharField(max_length=30, verbose_name='Telefon raqami....')),
                ('email', models.EmailField(max_length=254, verbose_name='Emaili...')),
                ('message', models.TextField(verbose_name='Xabari...')),
            ],
            options={
                'verbose_name': 'Aloqa',
                'verbose_name_plural': 'Aloqalar',
            },
        ),
    ]
