# Generated by Django 3.2.5 on 2021-08-09 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Shahar ismi...')),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
                ('image', models.ImageField(upload_to='media/cityImage/', verbose_name='Shahar rasmi...')),
            ],
            options={
                'verbose_name': 'Shahar',
                'verbose_name_plural': 'Shaharlar',
            },
        ),
        migrations.CreateModel(
            name='Grafik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Shaharlar nomi....')),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
                ('time', models.CharField(max_length=15, verbose_name='Vaqti...')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Narxi....')),
            ],
        ),
        migrations.CreateModel(
            name='TransportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mashina nomi...')),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
                ('image', models.ImageField(upload_to='media/carsImage/', verbose_name='Mashina rasmi...')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Narxi....')),
                ('first_time', models.CharField(max_length=6, verbose_name='Boshlanish vaqti...')),
                ('last_time', models.CharField(max_length=6, verbose_name='Tugash vaqti.....')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.transportcategory')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.city')),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transportlar',
            },
        ),
    ]
