# Generated by Django 3.2.5 on 2021-08-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_city_grafik_transport_transportcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grafik',
            options={'verbose_name': 'Grafik', 'verbose_name_plural': 'Grafiklar'},
        ),
    ]
