# Generated by Django 3.2.5 on 2021-08-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_grafik_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortGrafik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Shaharlar nomi....')),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
                ('time', models.CharField(max_length=15, verbose_name='Vaqti...')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Narxi....')),
            ],
            options={
                'verbose_name': 'FortGrafik',
                'verbose_name_plural': 'FortGrafiklar',
            },
        ),
        migrations.RenameModel(
            old_name='Grafik',
            new_name='BusGrafik',
        ),
        migrations.AlterModelOptions(
            name='busgrafik',
            options={'verbose_name': 'AvtobusGrafik', 'verbose_name_plural': 'AvtobusGrafiklar'},
        ),
    ]
